<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php

use SR\Widgets\Block\Adminhtml\Widget\Renderer\ColorPickerRenderer;

/**
 * @var $block ColorPickerRenderer
 */
?>
<?php
$element = $block->getElement();
$note = $element->getNote() ? '<div class="note admin__field-note" id="' . $element->getId() . '-note">' . $element->getNote() . '</div>' : '';
$elementBeforeLabel = $element->getExtType() == 'checkbox admin__control-checkbox' || $element->getExtType() == 'radio admin__control-radio';
$addOn = ($element->getBeforeElementHtml() || $element->getAfterElementHtml()) && !$element->getNoWrapAsAddon();
$fieldId = ($element->getHtmlContainerId()) ? ' id="' . $element->getHtmlContainerId() . '"' : '';
$fieldClass = "admin__field field field-{$element->getId()} {$element->getCssClass()}";
$fieldClass .= ($elementBeforeLabel) ? ' choice' : '';
$fieldClass .= ($addOn) ? ' with-addon' : '';
$fieldClass .= ($element->getRequired()) ? ' required _required' : '';
$fieldClass .= ($note) ? ' with-note' : '';
$fieldClass .= (!$element->getLabelHtml()) ? ' no-label' : '';

$fieldAttributes = $fieldId . ' class="' . $fieldClass . '" '
    . $block->getUiId('form-field', $element->getId())
    . ($element->getFieldExtraAttributes() ? ' ' . $element->getFieldExtraAttributes() : '');
?>

<?php if (!$element->getNoDisplay()): ?>
    <?php if ($element->getType() == 'hidden'): ?>
        <?= $element->getElementHtml() ?>
    <?php else: ?>
        <div<?= /* @escapeNotVerified */ $fieldAttributes ?>
                data-mage-init='{
                    "widgetColorPickerField": {
                        "fieldId": "<?= $element->getId() ?>",
                        "value": "<?= $element->getData('value') ?>"
                    }
                }'
        >
            <?= $element->getLabelHtml('', $element->getScopeLabel()) ?>
            <div class="admin__field-control control">
                <input id="<?php echo $element->getId(); ?>"
                       name="<?php echo $element->getName(); ?>"
                       value="<?php echo $element->getValue(); ?>"
                       class="widget-option input-text admin__control-text <?= $element->getRequired()? 'required-entry _required' : ''; ?>"
                />
                <?= /* @escapeNotVerified */ ($addOn) ? '<div class="admin__field">' . $element->getElementHtml() . '</div>' : $element->getElementHtml() ?>
                <?= /* @escapeNotVerified */ $note ?>
            </div>
        </div>
    <?php endif; ?>
<?php endif; ?>
