<?php
/**
 * Copyright © 2019 Studio Raz. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>
<?php

use SR\Widgets\Block\Widget\Banners;

/**
 * @var Banners $block
 */
?>
<?php
$title = $banner['title'];
$imagePath = $banner['image_path'];
$linkAddress = $banner['link_address'];
$linkLabel = $banner['link_label'];
$linkAttrs = $banner['link_open_link_in_new_tab'] ? 'target="_blank"' : '';
?>

<li class="banners-item-container <?= $bannersGridColumnClasses ?>">
    <div class="banners-item">
        <?php if ($imagePath): ?>
            <?php if ($linkAddress): ?>
                <a href="<?= $block->getUrl() . $linkAddress ?>" class="banners-item-image-container" title="<?= $linkLabel ?>" <?= $linkAttrs ?>>
            <?php else: ?>
                <div class="banners-item-image-container">
            <?php endif; ?>
                    <img src="<?= $block->getMedia($imagePath); ?>" class="banners-item-image" alt="<?= $linkLabel ?: $title ?>">
            <?php if ($linkAddress): ?>
                </a>
            <?php else: ?>
                </div>
            <?php endif; ?>
        <?php endif; ?>

        <?php if ($block->hasBannerTextContent($banner)): ?>
            <div class="banners-item-panel">
                <?php if ($title): ?>
                    <strong class="banners-item-title">
                        <span><?= $title ?></span>
                    </strong>
                <?php endif; ?>

                <?php if ($banner['description']): ?>
                    <p class="banners-item-description">
                        <span><?= $banner['description'] ?></span>
                    </p>
                <?php endif; ?>

                <?php if ($linkLabel && $linkAddress): ?>
                    <a href="<?= $block->getUrl() . $linkAddress ?>" class="banners-item-link" title="<?= $title ?>" <?= $linkAttrs ?>>
                        <span><?= $linkLabel ?></span>
                    </a>
                <?php endif; ?>
            </div>
        <?php endif; ?>
    </div>
</li>
