<?php
/**
 * Copyright © 2019 Studio Raz. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>
<?php

use SR\Widgets\Block\Widget\Banners;

/**
 * @var Banners $block
 */
?>
<?php
$primaryBannerTitle = $block->getData('primaryBannerTitle');
$primaryBannerDescription = $block->getData('primaryBannerDescription');
$primaryBannerLinkLabel = $block->getData('primaryBannerLinkLabel');
$primaryBannerLinkURL = $block->getData('primaryBannerLinkURL');
$primaryBannerLinkOpenLinkInNewTab = $block->getData('primaryBannerLinkOpenLinkInNewTab');
$primaryBannerImagePath = $block->getMedia($block->getData('primaryBannerImagePath'));
$primaryBannerLinkAttrs = $primaryBannerLinkOpenLinkInNewTab ? 'target="_blank"' : '';
$primaryBannerHasLink = $primaryBannerLinkLabel && $primaryBannerLinkURL;
?>

<div class="banners-primary-banner">
    <?php if ($primaryBannerHasLink): ?>
        <a href="<?= $block->_getUrl($primaryBannerLinkURL) ?>" class="banners-primary-banner-image-container"
           title="<?= $primaryBannerTitle ?>" <?= $primaryBannerLinkAttrs ?>>
    <?php else: ?>
        <div class="banners-primary-banner-image-container">
    <?php endif; ?>
            <img src="<?= $primaryBannerImagePath ?>" class="banners-primary-banner-image" alt="<?= $primaryBannerTitle ?>"/>
    <?php if ($primaryBannerHasLink): ?>
        </a>
    <?php else: ?>
        </div>
    <?php endif; ?>
    <span class="banners-primary-banner-content">
        <?php if ($primaryBannerTitle): ?>
            <strong class="banners-primary-banner-title"><?= $primaryBannerTitle ?></strong>
        <?php endif; ?>
        <?php if ($primaryBannerDescription): ?>
            <p class="banners-primary-banner-description"><?= $primaryBannerDescription ?></p>
        <?php endif; ?>
        <?php if ($primaryBannerHasLink): ?>
            <a href="<?= $block->_getUrl($primaryBannerLinkURL) ?>" class="banners-primary-banner-link" <?= $primaryBannerLinkAttrs ?>>
                <span><?= $primaryBannerLinkLabel ?></span>
            </a>
        <?php endif; ?>
    </span>
</div>
