<?php
/**
 * Copyright © 2019 Studio Raz. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>
<?php

use SR\Widgets\Block\Widget\Banners;

/**
 * @var Banners $block
 */
?>
<?php
$widgetId = uniqId('widget-');
$widgetCssClass = 'widget ' . $widgetId . ' ';
$widgetCssClass .= $this->getData('isFullWidth') ? ' full-width ' : '';
$widgetCssClass .= $this->getData('isSlider') ? ' banners-has-slider ' : '';
$widgetCssClass .= $block->hasPrimaryBanner() ? ' has-primary-banner ' : '';
$widgetCssClass .= $this->getData('cssClass');
$widgetTitle = $block->getData('widgetTitle');
$widgetBackgroundImage = $block->getData('widgetBackgroundImage');

$primaryBannerTitle = $block->getData('primaryBannerTitle');
$primaryBannerLinkLabel = $block->getData('primaryBannerLinkLabel');
$primaryBannerLinkURL = $block->getData('primaryBannerLinkURL');
$primaryBannerLinkOpenLinkInNewTab = $block->getData('primaryBannerLinkOpenLinkInNewTab');
$primaryBannerImagePath = $block->getMedia($block->getData('primaryBannerImagePath'));

$banners = $block->getItems();
$bannersAmount = $block->getItemsAmount();
$bannersGridRowClasses = 'widget-row';
$bannersGridColumnClasses = $this->getData('gridClasses');
$bannersSliderCssClass = $this->getData('isSlider') ? 'owl-carousel banners-slider' : '';
$bannersFooter = $block->getData('bannersFooter');

$sliderConfig = $this->getData('sliderConfig') ? '{' . $this->getData('sliderConfig') . '}' : '{}';
?>

<?php include($block->getTemplateFile('SR_Widgets::widget/widget_base_styles.phtml')) ?>

<div class="<?= $widgetCssClass ?>" data-widget-id="<?= $widgetId ?>">
    <div class="banners-container container">
        <?php if ($widgetTitle): ?>
            <strong class="banners-widget-title">
                <span><?= $widgetTitle ?></span>
            </strong>
        <?php endif; ?>
        <?php if ($block->hasPrimaryBanner()): ?>
            <?php $linkAttrs = $primaryBannerLinkOpenLinkInNewTab ? 'target="_blank"' : '' ?>
            <div class="banners-primary-banner">
                <a href="<?= $primaryBannerLinkURL ?>" class="banners-primary-banner-link"
                   title="<?= $primaryBannerTitle ?>" <?= $linkAttrs ?>>
                    <img src="<?= $primaryBannerImagePath ?>" class="banners-primary-banner-image" alt="<?= $primaryBannerTitle ?>"/>
                    <span class="banners-primary-banner-content">
                        <?php if ($primaryBannerTitle): ?>
                            <strong class="banners-primary-banner-title">
                                <?= $primaryBannerTitle ?>
                            </strong>
                        <?php endif; ?>
                        <?php if ($primaryBannerLinkLabel): ?>
                            <span class="banners-primary-banner-link-label">
                                <?= $primaryBannerLinkLabel ?>
                            </span>
                        <?php endif; ?>
                    </span>
                </a>
            </div>
        <?php endif; ?>
        <ul class="banners banners-<?= $bannersAmount ?>-items <?= $bannersGridRowClasses ?> <?= $bannersSliderCssClass ?>">
            <?php foreach ($banners as $banner): ?>
                <?php $linkAttrs = $banner['link_open_link_in_new_tab'] ? 'target="_blank"' : '' ?>
                <li class="<?= $bannersGridColumnClasses ?>">
                    <div class="banners-item">
                        <?php if ($banner['image_path']): ?>
                            <?php if ($banner['link_address']): ?>
                                <a href="<?= $block->getUrl() . $banner['link_address'] ?>" class="banners-item-image-container"
                                title="<?= $banner['link_label'] ?>" <?= $linkAttrs ?>>
                            <?php endif; ?>
                            <img src="<?= $block->getMedia($banner['image_path']); ?>" class="banners-item-image"
                                 alt="<?= $banner['link_label'] ?>">
                            <?php if ($banner['link_address']): ?>
                                </a>
                            <?php endif; ?>
                        <?php endif; ?>

                        <?php if ($banner['title'] || ($banner['link_label'] && $banner['link_address'])): ?>
                            <div class="banners-item-panel">
                                <?php if ($banner['title']): ?>
                                    <strong class="banners-item-title">
                                        <span><?= $banner['title'] ?></span>
                                    </strong>
                                <?php endif; ?>

                                <?php if ($banner['link_label'] && $banner['link_address']): ?>
                                    <a href="<?= $block->getUrl() . $banner['link_address'] ?>"
                                       class="banners-item-link"
                                       title="<?= $banner['title'] ?>" <?= $linkAttrs ?>>
                                        <span><?= $banner['link_label'] ?></span>
                                    </a>
                                <?php endif; ?>
                            </div>
                        <?php endif; ?>
                    </div>
                </li>
            <?php endforeach; ?>
        </ul>

        <?php if ($bannersFooter): ?>
            <div class="banners-footer"><?= html_entity_decode($bannersFooter) ?></div>
        <?php endif; ?>
    </div>
</div>

<?php if ($this->getData('isSlider')): ?>
    <?php include($block->getTemplateFile('SR_Widgets::widget/slider_assets_loader.phtml')) ?>

    <script>
        require([
            'jquery',
            'owlCarousel2'
        ], function ($) {
            $(document).ready(function () {
                $('.<?= $widgetId ?> .owl-carousel').owlCarousel(<?= $sliderConfig ?>);
            });
        });
    </script>
<?php endif; ?>
