<?php
/**
 * Copyright © 2019 Studio Raz. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>
<?php

use SR\Widgets\Block\Widget\Product\ProductsList;

/**
 * @var ProductsList $block
 */
?>
<?php
$widgetId = uniqId('widget-');
$widgetCssClass = 'widget ' . $widgetId . ' ';
$widgetCssClass .= $this->getData('isFullWidth') ? ' full-width ' : '';
$widgetCssClass .= $this->getData('cssClass');
$widgetBackgroundImage = $block->getData('widgetBackgroundImage');
$widgetHeader = $block->getData('widgetHeader');
$widgetFooter = $block->getData('widgetFooter');

$titleURL = $block->getData('titleURL');
$titleURLAddress = $block->_getUrl($titleURL);

$isSlider = $this->getData('isSlider');
$sliderConfig = $this->getData('sliderConfig') ? '{' . $this->getData('sliderConfig') . '}' : '{}';
?>

<?php include($block->getTemplateFile('SR_Widgets::widget/widget_base_styles.phtml')) ?>

<div class="<?= $widgetCssClass ?>" data-widget-id="<?= $widgetId ?>">
    <div class="block-products-list-container container">
        <?php if ($widgetHeader): ?>
            <div class="banners-header"><?= html_entity_decode($widgetHeader) ?></div>
        <?php endif; ?>

        <?php include($block->getTemplateFile('SR_Widgets::widget/product/content/grid.phtml')) ?>

        <?php if ($widgetFooter): ?>
            <div class="banners-footer"><?= html_entity_decode($widgetFooter) ?></div>
        <?php endif; ?>
    </div>
</div>

<?php if ($isSlider): ?>
    <?php include($block->getTemplateFile('SR_Widgets::widget/slider_assets_loader.phtml')) ?>

    <script>
        require([
            'jquery',
            'owlCarousel2'
        ], function ($) {
            $(document).ready(function () {
                var $slider = $('.<?= $widgetId ?> .product-items');
                $slider.addClass('owl-carousel');

                $('.<?= $widgetId ?> .owl-carousel').owlCarousel(<?= $sliderConfig ?>);
            });
        });
    </script>
<?php endif; ?>
