<?php
/**
 * Copyright © 2019 Studio Raz. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>
<?php

use SR\Widgets\Block\Widget\Product\ProductsList;

/**
 * @var ProductsList $block
 */
?>
<?php
$widgetId = uniqId('widget-');
$widgetCssClass = 'widget ' . $widgetId . ' ';
$widgetCssClass .= $this->getData('isFullWidth') ? ' full-width ' : '';
$widgetCssClass .= $this->getData('cssClass');
$widgetTitle = $block->getData('widgetTitle');
$widgetBackgroundImage = $block->getData('widgetBackgroundImage');
?>

<?php include($block->getTemplateFile('SR_Widgets::widget/widget_base_styles.phtml')) ?>

<div class="<?= $widgetCssClass ?>" data-widget-id="<?= $widgetId ?>">
    <div class="block-products-list-container container">
        <?php include($block->getTemplateFile('SR_Widgets::widget/product/content/grid.phtml')) ?>
    </div>
</div>
