<?php
/**
 * Copyright © 2019 Studio Raz. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>
<?php

use SR\Widgets\Block\Widget\SRCMSStaticBlock;

/**
 * @var SRCMSStaticBlock $block
 */
?>
<?php
$widgetId = uniqId('widget-');
$widgetCssClass = 'widget ' . $widgetId . ' ';
$widgetCssClass .= $this->getData('isFullWidth') ? ' full-width ' : '';
$widgetCssClass .= $this->getData('cssClass');
$widgetTitle = $block->getData('widgetTitle');
$widgetBackgroundImage = $block->getData('widgetBackgroundImage');
$widgetType = $this->getData('widgetType');
$widgetBlockInit = null;

$sliderConfig = $this->getData('sliderConfig') ? '{' . $this->getData('sliderConfig') . '}' : '{}';

if ($widgetType === 'collapsible_blocks_container') {
    $widgetBlockInit = 'data-mage-init=\'{
        "accordion":{
            "openedState": "active",
            "collapsible": true,
            "active": false,
            "multipleCollapsible": true,
            "animate": 200
        }
    }\'';
}
?>

<?php include($block->getTemplateFile('SR_Widgets::widget/widget_base_styles.phtml')) ?>

<div class="<?= $widgetCssClass ?>" data-widget-id="<?= $widgetId ?>">
    <div class="block-static-block-container container" <?= $widgetBlockInit ?>>
        <?php if ($widgetTitle): ?>
            <strong class="static-block-title">
                <span><?= $widgetTitle ?></span>
            </strong>
        <?php endif; ?>
        <?php include($block->getTemplateFile('SR_Widgets::widget/static_block/default.phtml')) ?>
    </div>
</div>

<?php if ($widgetType === 'slider_blocks_container'): ?>
    <?php include($block->getTemplateFile('SR_Widgets::widget/slider_assets_loader.phtml')) ?>

    <script>
        require([
            'jquery',
            'SR_Widgets/js/widgets-slider',
            'owlCarousel2'
        ], function ($, WidgetsSlider) {
            $(document).ready(function () {
                var $sliderContent = $('.<?= $widgetId ?> .block-static-block');

                WidgetsSlider($sliderContent);
                $('.<?= $widgetId ?> .owl-carousel').owlCarousel(<?= $sliderConfig ?>);
            });
        });
    </script>
<?php endif; ?>
